"""004 telegram channels alert logs maintenance

Revision ID: 208e02f76b2c
Revises: 9e741a0e50d1
Create Date: 2026-09-16 13:55:01.263898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208e02f76b2c'
down_revision: Union[str, Sequence[str], None] = '9e741a0e50d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type = 'telegram'", name=op.f('ck_notification_channels_type_telegram_only')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_notification_channels_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels'))
    )
    op.create_index('ix_notification_channels_team_id_type', 'notification_channels', ['team_id', 'type'], unique=False)
    op.create_table('maintenance_windows',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_maintenance_windows_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_maintenance_windows_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_maintenance_windows_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_windows'))
    )
    op.create_index('ix_maintenance_monitor_id', 'maintenance_windows', ['monitor_id'], unique=False)
    op.create_index('ix_maintenance_team_id_starts', 'maintenance_windows', ['team_id', 'starts_at'], unique=False)
    op.create_table('alert_logs',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('monitor_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('open','recovery','escalation','test')", name=op.f('ck_alert_logs_valid_alert_kind')),
    sa.CheckConstraint("status IN ('sent','failed','skipped')", name=op.f('ck_alert_logs_valid_alert_status')),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], name=op.f('fk_alert_logs_channel_id_notification_channels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_alert_logs_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_alert_logs_monitor_id_monitors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_alert_logs_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_logs'))
    )
    op.create_index('ix_alert_logs_channel_id', 'alert_logs', ['channel_id'], unique=False)
    op.create_index('ix_alert_logs_incident_id', 'alert_logs', ['incident_id'], unique=False)
    op.create_index('ix_alert_logs_team_id_sent_at', 'alert_logs', ['team_id', 'sent_at'], unique=False)
    op.add_column('incidents', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'escalated_at')
    op.drop_index('ix_alert_logs_team_id_sent_at', table_name='alert_logs')
    op.drop_index('ix_alert_logs_incident_id', table_name='alert_logs')
    op.drop_index('ix_alert_logs_channel_id', table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index('ix_maintenance_team_id_starts', table_name='maintenance_windows')
    op.drop_index('ix_maintenance_monitor_id', table_name='maintenance_windows')
    op.drop_table('maintenance_windows')
    op.drop_index('ix_notification_channels_team_id_type', table_name='notification_channels')
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
