"""005 heartbeats

Revision ID: 3241a637104e
Revises: 208e02f76b2c
Create Date: 2026-09-17 01:50:26.209765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3241a637104e'
down_revision: Union[str, Sequence[str], None] = '208e02f76b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeats',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ping_key', sa.String(length=64), nullable=False),
    sa.Column('period_min', sa.Integer(), nullable=False),
    sa.Column('grace_min', sa.Integer(), nullable=False),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ALIVE', 'MISSING')", name=op.f('ck_heartbeats_valid_hb_status')),
    sa.CheckConstraint('grace_min >= 0 AND grace_min <= 1440', name=op.f('ck_heartbeats_valid_hb_grace')),
    sa.CheckConstraint('period_min >= 1 AND period_min <= 10080', name=op.f('ck_heartbeats_valid_hb_period')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_heartbeats_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heartbeats'))
    )
    op.create_index(op.f('ix_heartbeats_ping_key'), 'heartbeats', ['ping_key'], unique=True)
    op.create_index('ix_heartbeats_team_id', 'heartbeats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_heartbeats_team_id', table_name='heartbeats')
    op.drop_index(op.f('ix_heartbeats_ping_key'), table_name='heartbeats')
    op.drop_table('heartbeats')
    # ### end Alembic commands ###
