"""003 incidents

Revision ID: 9e741a0e50d1
Revises: b50beb9eaf3f
Create Date: 2026-09-15 22:12:59.047601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e741a0e50d1'
down_revision: Union[str, Sequence[str], None] = 'b50beb9eaf3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE (Phase 10): this migration shipped as an empty `pass`, so the
    # incidents table only ever existed in long-lived dev DBs (via create_all).
    # Fresh databases (Neon) exposed the gap when 004's FKs referenced it.
    # Backfilled here with exactly what the Incident model declares. Safe for
    # existing DBs: they never re-run an applied revision.
    # ### backfilled to match app/models/incident.py ###
    op.create_table('incidents',
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downtime_sec', sa.Integer(), nullable=True),
    # NOTE: escalated_at is deliberately NOT here — 004 adds it (fresh DBs must
    # replay the same order). ai_summary IS here — no other migration adds it.
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'ACK', 'RESOLVED')", name=op.f('ck_incidents_valid_incident_status')),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_incidents_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_incidents_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index('ix_incidents_monitor_id_status', 'incidents', ['monitor_id', 'status'], unique=False)
    op.create_index('ix_incidents_team_id_started_at', 'incidents', ['team_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_team_id_started_at', table_name='incidents')
    op.drop_index('ix_incidents_monitor_id_status', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
