"""002 monitors checks

Revision ID: b50beb9eaf3f
Revises: 0d3786a49620
Create Date: 2026-09-13 15:53:51.028247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50beb9eaf3f'
down_revision: Union[str, Sequence[str], None] = '0d3786a49620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('interval_min', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('ssl_check', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('interval_min IN (1, 5, 10, 30)', name=op.f('ck_monitors_valid_interval')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_monitors_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitors'))
    )
    op.create_index(op.f('ix_monitors_team_id'), 'monitors', ['team_id'], unique=False)
    op.create_table('checks',
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_checks_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checks'))
    )
    op.create_index('ix_checks_brin_checked_at', 'checks', ['checked_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_checks_monitor_id_checked_at', 'checks', ['monitor_id', 'checked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checks_monitor_id_checked_at', table_name='checks')
    op.drop_index('ix_checks_brin_checked_at', table_name='checks', postgresql_using='brin')
    op.drop_table('checks')
    op.drop_index(op.f('ix_monitors_team_id'), table_name='monitors')
    op.drop_table('monitors')
    # ### end Alembic commands ###
